/*
 * This file was generated by the Gradle 'init' task. UWU TESTING GITHUB
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.jgrapht:jgrapht-core:1.5.2")

    // JavaFX controls & media
    implementation("org.openjfx:javafx-controls:21")
    implementation("org.openjfx:javafx-media:21")

    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {                       // ★ ให้ Gradle ดึง JavaFX 21 ให้เรา
    version = "21"
    modules = listOf(
        "javafx.controls",
        "javafx.media"
    )
}

application {
    // Define the main class for the application.
    mainClass = "app.Main"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
